[2025-10-29T14:22:04.120+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_elastic_gcs.PutElasticSearch scheduled__2025-10-29T14:21:00+00:00 [queued]>
[2025-10-29T14:22:04.130+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_elastic_gcs.PutElasticSearch scheduled__2025-10-29T14:21:00+00:00 [queued]>
[2025-10-29T14:22:04.131+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-29T14:22:04.147+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): PutElasticSearch> on 2025-10-29 14:21:00+00:00
[2025-10-29T14:22:04.155+0000] {standard_task_runner.py:60} INFO - Started process 280 to run task
[2025-10-29T14:22:04.159+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_elastic_gcs', 'PutElasticSearch', 'scheduled__2025-10-29T14:21:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/dag2_elastic_gcs_ingestion.py', '--cfg-path', '/tmp/tmp2811h5p9']
[2025-10-29T14:22:04.165+0000] {standard_task_runner.py:88} INFO - Job 266: Subtask PutElasticSearch
[2025-10-29T14:22:04.238+0000] {task_command.py:423} INFO - Running <TaskInstance: dag2_kafka_elastic_gcs.PutElasticSearch scheduled__2025-10-29T14:21:00+00:00 [running]> on host c91e5c2c38a7
[2025-10-29T14:22:04.348+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_elastic_gcs' AIRFLOW_CTX_TASK_ID='PutElasticSearch' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T14:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T14:21:00+00:00'
[2025-10-29T14:22:04.355+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/operators/python.py:216 AirflowProviderDeprecationWarning: This class is deprecated.
            Please use `***.providers.elasticsearch.hooks.elasticsearch.ElasticsearchSQLHook`.
[2025-10-29T14:22:04.366+0000] {base.py:83} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2025-10-29T14:22:04.368+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag2_elastic_gcs_ingestion.py", line 104, in put_elasticsearch
    es = Elasticsearch(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 333, in __init__
    node_configs = client_node_configs(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 108, in client_node_configs
    node_configs = hosts_to_node_configs(hosts)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 157, in hosts_to_node_configs
    node_configs.append(host_mapping_to_node_config(host))
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 224, in host_mapping_to_node_config
    return NodeConfig(**options)  # type: ignore
TypeError: __init__() missing 1 required positional argument: 'scheme'
[2025-10-29T14:22:04.385+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag2_kafka_elastic_gcs, task_id=PutElasticSearch, execution_date=20251029T142100, start_date=20251029T142204, end_date=20251029T142204
[2025-10-29T14:22:04.398+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 266 for task PutElasticSearch (__init__() missing 1 required positional argument: 'scheme'; 280)
[2025-10-29T14:22:04.414+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-29T14:22:04.437+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
