[2025-10-28T23:35:00.709+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:34:00+00:00 [queued]>
[2025-10-28T23:35:00.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:34:00+00:00 [queued]>
[2025-10-28T23:35:00.718+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T23:35:00.732+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 23:34:00+00:00
[2025-10-28T23:35:00.740+0000] {standard_task_runner.py:60} INFO - Started process 237 to run task
[2025-10-28T23:35:00.745+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-28T23:34:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmp9sqrziwi']
[2025-10-28T23:35:00.747+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask ConsumKafka
[2025-10-28T23:35:00.816+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:34:00+00:00 [running]> on host 9680281a20bc
[2025-10-28T23:35:00.915+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T23:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T23:34:00+00:00'
[2025-10-28T23:35:00.921+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:35:00.927+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
[2025-10-28T23:35:00.927+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:35:00.929+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('source',)
[2025-10-28T23:35:00.930+0000] {dag1_kafka_processing.py:71} INFO - Consommateur Kafka créé pour le topic 'source'. En attente de messages...
[2025-10-28T23:35:00.934+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:35:00.934+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:35:00.935+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:35:01.039+0000] {cluster.py:401} INFO - Coordinator for group/***-consumers is ('coordinator-1', 'kafka', 9092, None)
[2025-10-28T23:35:01.040+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group ***-consumers
[2025-10-28T23:35:01.041+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-10-28T23:35:01.042+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers
[2025-10-28T23:35:01.043+0000] {base.py:419} INFO - Failed to join group ***-consumers: NodeNotReadyError: coordinator-1
[2025-10-28T23:35:01.045+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:35:01.046+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:35:01.147+0000] {base.py:532} INFO - (Re-)joining group ***-consumers
[2025-10-28T23:35:01.150+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-2e70741f-e9c4-4421-9783-942bf2e8f9cb for group ***-consumers; will retry join-group
[2025-10-28T23:35:01.151+0000] {base.py:419} INFO - Failed to join group ***-consumers: [Error 79] MemberIdRequiredError
[2025-10-28T23:35:01.152+0000] {base.py:532} INFO - (Re-)joining group ***-consumers
[2025-10-28T23:35:04.158+0000] {base.py:594} INFO - Successfully joined group ***-consumers <Generation 4 (member_id: kafka-python-2.2.15-2e70741f-e9c4-4421-9783-942bf2e8f9cb, protocol: range)>
[2025-10-28T23:35:04.158+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-10-28T23:35:04.163+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('source', 0)]
[2025-10-28T23:35:04.164+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('source', 0),) for group ***-consumers
[2025-10-28T23:35:10.935+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-10-28T23:35:10.936+0000] {base.py:891} INFO - Leaving consumer group (***-consumers).
[2025-10-28T23:35:10.940+0000] {base.py:906} INFO - LeaveGroup request for group ***-consumers returned successfully
[2025-10-28T23:35:10.941+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:35:10.941+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>
[2025-10-28T23:35:10.943+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:35:10.944+0000] {dag1_kafka_processing.py:77} WARNING - Aucun message reçu du topic 'source'. Le DAG s'arrêtera.
[2025-10-28T23:35:10.945+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-28T23:35:10.956+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T233400, start_date=20251028T233500, end_date=20251028T233510
[2025-10-28T23:35:11.016+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-28T23:35:11.045+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
