[2025-10-29T08:47:00.687+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-29T08:46:00+00:00 [queued]>
[2025-10-29T08:47:00.697+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-29T08:46:00+00:00 [queued]>
[2025-10-29T08:47:00.697+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-29T08:47:00.722+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-29 08:46:00+00:00
[2025-10-29T08:47:00.730+0000] {standard_task_runner.py:60} INFO - Started process 1344 to run task
[2025-10-29T08:47:00.734+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-29T08:46:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmp2m65obt2']
[2025-10-29T08:47:00.736+0000] {standard_task_runner.py:88} INFO - Job 153: Subtask ConsumKafka
[2025-10-29T08:47:00.799+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-29T08:46:00+00:00 [running]> on host 9680281a20bc
[2025-10-29T08:47:00.896+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T08:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T08:46:00+00:00'
[2025-10-29T08:47:00.900+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-29T08:47:00.904+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
[2025-10-29T08:47:00.904+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-29T08:47:00.906+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('source',)
[2025-10-29T08:47:00.907+0000] {dag1_kafka_processing.py:71} INFO - Consommateur Kafka créé pour le topic 'source'. En attente de messages...
[2025-10-29T08:47:00.910+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-29T08:47:00.911+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-29T08:47:00.912+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-29T08:47:01.015+0000] {cluster.py:401} INFO - Coordinator for group/***-consumers-dag1 is ('coordinator-1', 'kafka', 9092, None)
[2025-10-29T08:47:01.016+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group ***-consumers-dag1
[2025-10-29T08:47:01.017+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-10-29T08:47:01.018+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers-dag1
[2025-10-29T08:47:01.018+0000] {base.py:419} INFO - Failed to join group ***-consumers-dag1: NodeNotReadyError: coordinator-1
[2025-10-29T08:47:01.020+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-29T08:47:01.021+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-29T08:47:01.122+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-29T08:47:01.125+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-7c85f20f-837b-4b4b-9c9f-49e5f55ee890 for group ***-consumers-dag1; will retry join-group
[2025-10-29T08:47:01.126+0000] {base.py:419} INFO - Failed to join group ***-consumers-dag1: [Error 79] MemberIdRequiredError
[2025-10-29T08:47:01.126+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-29T08:47:04.131+0000] {base.py:594} INFO - Successfully joined group ***-consumers-dag1 <Generation 56 (member_id: kafka-python-2.2.15-7c85f20f-837b-4b4b-9c9f-49e5f55ee890, protocol: range)>
[2025-10-29T08:47:04.133+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-10-29T08:47:04.140+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('source', 0)]
[2025-10-29T08:47:04.142+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('source', 0),) for group ***-consumers-dag1
[2025-10-29T08:47:30.911+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-10-29T08:47:30.913+0000] {base.py:891} INFO - Leaving consumer group (***-consumers-dag1).
[2025-10-29T08:47:30.916+0000] {base.py:906} INFO - LeaveGroup request for group ***-consumers-dag1 returned successfully
[2025-10-29T08:47:30.917+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-29T08:47:30.919+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>
[2025-10-29T08:47:30.919+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-29T08:47:30.920+0000] {dag1_kafka_processing.py:77} WARNING - Aucun message reçu du topic 'source'. Le DAG s'arrêtera.
[2025-10-29T08:47:30.921+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-29T08:47:30.939+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251029T084600, start_date=20251029T084700, end_date=20251029T084730
[2025-10-29T08:47:30.980+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-29T08:47:31.012+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
