[2025-10-28T21:28:00.821+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T21:27:00+00:00 [queued]>
[2025-10-28T21:28:00.827+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T21:27:00+00:00 [queued]>
[2025-10-28T21:28:00.828+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T21:28:00.838+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 21:27:00+00:00
[2025-10-28T21:28:00.844+0000] {standard_task_runner.py:60} INFO - Started process 359 to run task
[2025-10-28T21:28:00.850+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-28T21:27:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmpwxaoyzjt']
[2025-10-28T21:28:00.853+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask ConsumKafka
[2025-10-28T21:28:00.922+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T21:27:00+00:00 [running]> on host bbaff9837f1f
[2025-10-28T21:28:01.005+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T21:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T21:27:00+00:00'
[2025-10-28T21:28:01.012+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.21.0.4', 29092)]>: connecting to kafka:29092 [('172.21.0.4', 29092) IPv4]
[2025-10-28T21:28:01.018+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.21.0.4', 29092)]>: Broker version identified as 2.6
[2025-10-28T21:28:01.019+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>: Connection complete.
[2025-10-28T21:28:01.020+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('source',)
[2025-10-28T21:28:01.021+0000] {dag1_kafka_processing.py:71} INFO - Consommateur Kafka créé pour le topic 'source'. En attente de messages...
[2025-10-28T21:28:01.024+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.21.0.4', 29092)]>: connecting to kafka:29092 [('172.21.0.4', 29092) IPv4]
[2025-10-28T21:28:01.025+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>: Connection complete.
[2025-10-28T21:28:01.025+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>: Closing connection. 
[2025-10-28T21:28:01.128+0000] {cluster.py:401} INFO - Coordinator for group/***-consumers is ('coordinator-1', 'kafka', 29092, None)
[2025-10-28T21:28:01.129+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group ***-consumers
[2025-10-28T21:28:01.129+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-10-28T21:28:01.130+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers
[2025-10-28T21:28:01.131+0000] {base.py:419} INFO - Failed to join group ***-consumers: NodeNotReadyError: coordinator-1
[2025-10-28T21:28:01.132+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:29092 <connecting> [IPv4 ('172.21.0.4', 29092)]>: connecting to kafka:29092 [('172.21.0.4', 29092) IPv4]
[2025-10-28T21:28:01.133+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>: Connection complete.
[2025-10-28T21:28:01.234+0000] {base.py:532} INFO - (Re-)joining group ***-consumers
[2025-10-28T21:28:01.237+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-1f747c03-cc94-4c33-84d5-f0efc1ed2c78 for group ***-consumers; will retry join-group
[2025-10-28T21:28:01.238+0000] {base.py:419} INFO - Failed to join group ***-consumers: [Error 79] MemberIdRequiredError
[2025-10-28T21:28:01.238+0000] {base.py:532} INFO - (Re-)joining group ***-consumers
[2025-10-28T21:28:04.245+0000] {base.py:594} INFO - Successfully joined group ***-consumers <Generation 5 (member_id: kafka-python-2.2.15-1f747c03-cc94-4c33-84d5-f0efc1ed2c78, protocol: range)>
[2025-10-28T21:28:04.246+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-10-28T21:28:04.251+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('source', 0)]
[2025-10-28T21:28:04.255+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('source', 0),) for group ***-consumers
[2025-10-28T21:28:11.025+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-10-28T21:28:11.026+0000] {base.py:891} INFO - Leaving consumer group (***-consumers).
[2025-10-28T21:28:11.028+0000] {base.py:906} INFO - LeaveGroup request for group ***-consumers returned successfully
[2025-10-28T21:28:11.029+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>: Closing connection. 
[2025-10-28T21:28:11.030+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>
[2025-10-28T21:28:11.030+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:29092 <connected> [IPv4 ('172.21.0.4', 29092)]>: Closing connection. 
[2025-10-28T21:28:11.031+0000] {dag1_kafka_processing.py:77} WARNING - Aucun message reçu du topic 'source'. Le DAG s'arrêtera.
[2025-10-28T21:28:11.031+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-28T21:28:11.040+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T212700, start_date=20251028T212800, end_date=20251028T212811
[2025-10-28T21:28:11.073+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-28T21:28:11.094+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
