[2025-10-28T23:34:21.441+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:33:00+00:00 [queued]>
[2025-10-28T23:34:21.452+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:33:00+00:00 [queued]>
[2025-10-28T23:34:21.452+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T23:34:21.467+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 23:33:00+00:00
[2025-10-28T23:34:21.475+0000] {standard_task_runner.py:60} INFO - Started process 194 to run task
[2025-10-28T23:34:21.487+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-28T23:33:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmp7gbk3jzh']
[2025-10-28T23:34:21.490+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask ConsumKafka
[2025-10-28T23:34:21.624+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:33:00+00:00 [running]> on host 9680281a20bc
[2025-10-28T23:34:21.765+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T23:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T23:33:00+00:00'
[2025-10-28T23:34:21.772+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:34:21.795+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
[2025-10-28T23:34:21.797+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:34:21.799+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('source',)
[2025-10-28T23:34:21.800+0000] {dag1_kafka_processing.py:71} INFO - Consommateur Kafka créé pour le topic 'source'. En attente de messages...
[2025-10-28T23:34:21.876+0000] {cluster.py:313} WARNING - Topic source is not available during auto-create initialization
[2025-10-28T23:34:21.878+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:34:21.879+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:34:21.880+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:34:23.205+0000] {cluster.py:401} INFO - Coordinator for group/***-consumers is ('coordinator-1', 'kafka', 9092, None)
[2025-10-28T23:34:23.206+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group ***-consumers
[2025-10-28T23:34:23.207+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-10-28T23:34:23.209+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers
[2025-10-28T23:34:23.210+0000] {base.py:419} INFO - Failed to join group ***-consumers: NodeNotReadyError: coordinator-1
[2025-10-28T23:34:23.211+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:34:23.212+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:34:23.313+0000] {base.py:532} INFO - (Re-)joining group ***-consumers
[2025-10-28T23:34:23.337+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-99b6a634-14b5-4dda-974a-858dd3b61522 for group ***-consumers; will retry join-group
[2025-10-28T23:34:23.338+0000] {base.py:419} INFO - Failed to join group ***-consumers: [Error 79] MemberIdRequiredError
[2025-10-28T23:34:23.341+0000] {base.py:532} INFO - (Re-)joining group ***-consumers
[2025-10-28T23:34:29.376+0000] {base.py:594} INFO - Successfully joined group ***-consumers <Generation 1 (member_id: kafka-python-2.2.15-99b6a634-14b5-4dda-974a-858dd3b61522, protocol: range)>
[2025-10-28T23:34:29.377+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-10-28T23:34:29.378+0000] {range.py:47} WARNING - No partition metadata for topic source
[2025-10-28T23:34:29.445+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-10-28T23:34:29.446+0000] {consumer.py:249} INFO - Setting newly assigned partitions () for group ***-consumers
[2025-10-28T23:34:31.802+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-10-28T23:34:31.804+0000] {base.py:891} INFO - Leaving consumer group (***-consumers).
[2025-10-28T23:34:31.813+0000] {base.py:906} INFO - LeaveGroup request for group ***-consumers returned successfully
[2025-10-28T23:34:31.814+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:34:31.815+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:34:31.816+0000] {dag1_kafka_processing.py:77} WARNING - Aucun message reçu du topic 'source'. Le DAG s'arrêtera.
[2025-10-28T23:34:31.817+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-28T23:34:31.831+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T233300, start_date=20251028T233421, end_date=20251028T233431
[2025-10-28T23:34:31.883+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-28T23:34:31.914+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
