[2025-10-28T23:53:57.937+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:52:00+00:00 [queued]>
[2025-10-28T23:53:57.945+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:52:00+00:00 [queued]>
[2025-10-28T23:53:57.945+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T23:53:57.959+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 23:52:00+00:00
[2025-10-28T23:53:57.966+0000] {standard_task_runner.py:60} INFO - Started process 354 to run task
[2025-10-28T23:53:57.970+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-28T23:52:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmpe08i3hst']
[2025-10-28T23:53:57.973+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask ConsumKafka
[2025-10-28T23:53:58.054+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T23:52:00+00:00 [running]> on host 9680281a20bc
[2025-10-28T23:53:58.157+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T23:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T23:52:00+00:00'
[2025-10-28T23:53:58.162+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:53:58.166+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
[2025-10-28T23:53:58.167+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:53:58.168+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('source',)
[2025-10-28T23:53:58.169+0000] {dag1_kafka_processing.py:71} INFO - Consommateur Kafka créé pour le topic 'source'. En attente de messages...
[2025-10-28T23:53:58.173+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:53:58.174+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:53:58.175+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:53:58.278+0000] {cluster.py:401} INFO - Coordinator for group/***-consumers-dag1 is ('coordinator-1', 'kafka', 9092, None)
[2025-10-28T23:53:58.278+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group ***-consumers-dag1
[2025-10-28T23:53:58.279+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-10-28T23:53:58.280+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers-dag1
[2025-10-28T23:53:58.280+0000] {base.py:419} INFO - Failed to join group ***-consumers-dag1: NodeNotReadyError: coordinator-1
[2025-10-28T23:53:58.282+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:53:58.283+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:53:58.384+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:53:58.388+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-706eccd6-692a-4056-9d30-043d3584b732 for group ***-consumers-dag1; will retry join-group
[2025-10-28T23:53:58.389+0000] {base.py:419} INFO - Failed to join group ***-consumers-dag1: [Error 79] MemberIdRequiredError
[2025-10-28T23:53:58.389+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:54:01.395+0000] {base.py:594} INFO - Successfully joined group ***-consumers-dag1 <Generation 22 (member_id: kafka-python-2.2.15-706eccd6-692a-4056-9d30-043d3584b732, protocol: range)>
[2025-10-28T23:54:01.397+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-10-28T23:54:01.401+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-10-28T23:54:01.402+0000] {consumer.py:249} INFO - Setting newly assigned partitions () for group ***-consumers-dag1
[2025-10-28T23:54:04.406+0000] {base.py:951} WARNING - Heartbeat failed for group ***-consumers-dag1 because it is rebalancing
[2025-10-28T23:54:04.407+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers-dag1
[2025-10-28T23:54:04.407+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:54:04.431+0000] {base.py:594} INFO - Successfully joined group ***-consumers-dag1 <Generation 23 (member_id: kafka-python-2.2.15-706eccd6-692a-4056-9d30-043d3584b732, protocol: range)>
[2025-10-28T23:54:04.432+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-10-28T23:54:04.436+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-10-28T23:54:04.437+0000] {consumer.py:249} INFO - Setting newly assigned partitions () for group ***-consumers-dag1
[2025-10-28T23:54:28.169+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-10-28T23:54:28.170+0000] {base.py:891} INFO - Leaving consumer group (***-consumers-dag1).
[2025-10-28T23:54:28.174+0000] {base.py:906} INFO - LeaveGroup request for group ***-consumers-dag1 returned successfully
[2025-10-28T23:54:28.175+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:54:28.176+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:54:28.176+0000] {dag1_kafka_processing.py:77} WARNING - Aucun message reçu du topic 'source'. Le DAG s'arrêtera.
[2025-10-28T23:54:28.177+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-28T23:54:28.188+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T235200, start_date=20251028T235357, end_date=20251028T235428
[2025-10-28T23:54:28.223+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-28T23:54:28.253+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
